### ISSUE TITLE
抱歉，请问可以简单列一下各平台的使用方法吗？

### ISSUE THREAD

**Issue by laincat** [lifetyper/AsyncHttpsDNS#1]
_呃，虽然不应该发在这里，但是真的想试试这个项目..._

可以介绍一下在 Wiondows，LEDE 路由，Docker 等等场景 使用方式么？感激。

**Comment by lifetyper** [comment]
只要有python3环境，pip3 install asynchttpsdns就可以使用了，windows/mac都一样，linux应该一样只是没试过。docker我不会。lede基本没有考虑，那个python3版本太低而且是裁剪的。
		

		Get Outlook for iOS
	





On Wed, May 3, 2017 at 11:32 AM +0800, "laincat" <notifications@github.com> wrote:












呃，虽然不应该发在这里，但是真的想试试这个项目...


可以介绍一下在 Wiondows，LEDE 路由，Docker 等等场景 使用方式么？感激。

**Comment by laincat** [comment]
好的。

====

`pip3 install asynchttpsdns
Collecting asynchttpsdns
  Using cached AsyncHttpsDNS-0.0.8-py3-none-any.whl
Collecting args>=0.1.0 (from asynchttpsdns)
  Using cached args-0.1.0.tar.gz
Collecting retry>=0.9.2 (from asynchttpsdns)
  Using cached retry-0.9.2-py2.py3-none-any.whl
Requirement already satisfied: dnslib>=0.9.7 in c:\lang\python36\lib\site-packages (from asynchttpsdns)
Collecting cachetools>=2.0.0 (from asynchttpsdns)
  Using cached cachetools-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: dnspython>=1.15.0 in c:\lang\python36\lib\site-packages (from asynchttpsdns)
Collecting aiosocks==0.2.2 (from asynchttpsdns)
  Using cached aiosocks-0.2.2.tar.gz
Collecting aiodns>=1.1.1 (from asynchttpsdns)
  Using cached aiodns-1.1.1-py2.py3-none-any.whl
Collecting aiohttp>=2.0.7 (from asynchttpsdns)
  Using cached aiohttp-2.0.7.tar.gz
Collecting decorator>=3.4.2 (from retry>=0.9.2->asynchttpsdns)
  Using cached decorator-4.0.11-py2.py3-none-any.whl
Collecting py<2.0.0,>=1.4.26 (from retry>=0.9.2->asynchttpsdns)
  Using cached py-1.4.33-py2.py3-none-any.whl
Collecting pycares>=1.0.0 (from aiodns>=1.1.1->asynchttpsdns)
  Using cached pycares-2.1.1.tar.gz
Collecting chardet (from aiohttp>=2.0.7->asynchttpsdns)
  Using cached chardet-3.0.2-py2.py3-none-any.whl
Collecting multidict>=2.1.4 (from aiohttp>=2.0.7->asynchttpsdns)
  Using cached multidict-2.1.4.tar.gz
Collecting async_timeout>=1.2.0 (from aiohttp>=2.0.7->asynchttpsdns)
  Using cached async_timeout-1.2.1-py3-none-any.whl
Collecting yarl<0.11,>=0.10.0 (from aiohttp>=2.0.7->asynchttpsdns)
  Using cached yarl-0.10.0.tar.gz
Installing collected packages: args, decorator, py, retry, cachetools, aiosocks, pycares, aiodns, chardet, multidict, async-timeout, yarl, aiohttp, asynchttpsdns
  Running setup.py install for args ... done
  Running setup.py install for aiosocks ... done
  Running setup.py install for pycares ... error
    Complete output from command c:\lang\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Temp\\pip-build-i30xh34v\\pycares\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Temp\pip-g8k41hj6-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pycares
    copying pycares\errno.py -> build\lib.win-amd64-3.6\pycares
    copying pycares\_version.py -> build\lib.win-amd64-3.6\pycares
    copying pycares\__init__.py -> build\lib.win-amd64-3.6\pycares
    running build_ext
    building 'pycares._core' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    creating build\temp.win-amd64-3.6\Release\deps
    creating build\temp.win-amd64-3.6\Release\deps\c-ares
    creating build\temp.win-amd64-3.6\Release\deps\c-ares\src
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DHAVE_CONFIG_H=1 -Ic:\lang\python36\include -Ic:\lang\python36\include -Ideps\c-ares\src -Ideps\c-ares\src/config_win32 /Tcsrc/pycares.c /Fobuild\temp.win-amd64-3.6\Release\src/pycares.obj
    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
Command "c:\lang\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Temp\\pip-build-i30xh34v\\pycares\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Temp\pip-g8k41hj6-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Temp\pip-build-i30xh34v\pycares\`

**Comment by lifetyper** [comment]
python不要用64位的，坑不是一般多。
		

		Get Outlook for iOS
	





On Wed, May 3, 2017 at 11:53 AM +0800, "laincat" <notifications@github.com> wrote:












好的。


====


`pip3 install asynchttpsdns

Collecting asynchttpsdns

Using cached AsyncHttpsDNS-0.0.8-py3-none-any.whl

Collecting args>=0.1.0 (from asynchttpsdns)

Using cached args-0.1.0.tar.gz

Collecting retry>=0.9.2 (from asynchttpsdns)

Using cached retry-0.9.2-py2.py3-none-any.whl

Requirement already satisfied: dnslib>=0.9.7 in c:\lang\python36\lib\site-packages (from asynchttpsdns)

Collecting cachetools>=2.0.0 (from asynchttpsdns)

Using cached cachetools-2.0.0-py2.py3-none-any.whl

Requirement already satisfied: dnspython>=1.15.0 in c:\lang\python36\lib\site-packages (from asynchttpsdns)

Collecting aiosocks==0.2.2 (from asynchttpsdns)

Using cached aiosocks-0.2.2.tar.gz

Collecting aiodns>=1.1.1 (from asynchttpsdns)

Using cached aiodns-1.1.1-py2.py3-none-any.whl

Collecting aiohttp>=2.0.7 (from asynchttpsdns)

Using cached aiohttp-2.0.7.tar.gz

Collecting decorator>=3.4.2 (from retry>=0.9.2->asynchttpsdns)

Using cached decorator-4.0.11-py2.py3-none-any.whl

Collecting py<2.0.0,>=1.4.26 (from retry>=0.9.2->asynchttpsdns)

Using cached py-1.4.33-py2.py3-none-any.whl

Collecting pycares>=1.0.0 (from aiodns>=1.1.1->asynchttpsdns)

Using cached pycares-2.1.1.tar.gz

Collecting chardet (from aiohttp>=2.0.7->asynchttpsdns)

Using cached chardet-3.0.2-py2.py3-none-any.whl

Collecting multidict>=2.1.4 (from aiohttp>=2.0.7->asynchttpsdns)

Using cached multidict-2.1.4.tar.gz

Collecting async_timeout>=1.2.0 (from aiohttp>=2.0.7->asynchttpsdns)

Using cached async_timeout-1.2.1-py3-none-any.whl

Collecting yarl<0.11,>=0.10.0 (from aiohttp>=2.0.7->asynchttpsdns)

Using cached yarl-0.10.0.tar.gz

Installing collected packages: args, decorator, py, retry, cachetools, aiosocks, pycares, aiodns, chardet, multidict, async-timeout, yarl, aiohttp, asynchttpsdns

Running setup.py install for args ... done

Running setup.py install for aiosocks ... done

Running setup.py install for pycares ... error

Complete output from command c:\lang\python36\python.exe -u -c "import setuptools, tokenize;file='C:\Temp\pip-build-i30xh34v\pycares\setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r
', '
');f.close();exec(compile(code, file, 'exec'))" install --record C:\Temp\pip-g8k41hj6-record\install-record.txt --single-version-externally-managed --compile:

running install

running build

running build_py

creating build

creating build\lib.win-amd64-3.6

creating build\lib.win-amd64-3.6\pycares

copying pycares\errno.py -> build\lib.win-amd64-3.6\pycares

copying pycares_version.py -> build\lib.win-amd64-3.6\pycares

copying pycares_init_.py -> build\lib.win-amd64-3.6\pycares

running build_ext

building 'pycares._core' extension

creating build\temp.win-amd64-3.6

creating build\temp.win-amd64-3.6\Release

creating build\temp.win-amd64-3.6\Release\src

creating build\temp.win-amd64-3.6\Release\deps

creating build\temp.win-amd64-3.6\Release\deps\c-ares

creating build\temp.win-amd64-3.6\Release\deps\c-ares\src

cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DHAVE_CONFIG_H=1 -Ic:\lang\python36\include -Ic:\lang\python36\include -Ideps\c-ares\src -Ideps\c-ares\src/config_win32 /Tcsrc/pycares.c /Fobuild\temp.win-amd64-3.6\Release\src/pycares.obj

error: command 'cl.exe' failed: No such file or directory
----------------------------------------



Command "c:\lang\python36\python.exe -u -c "import setuptools, tokenize;file='C:\Temp\pip-build-i30xh34v\pycares\setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r
', '
');f.close();exec(compile(code, file, 'exec'))" install --record C:\Temp\pip-g8k41hj6-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Temp\pip-build-i30xh34v\pycares`

**Comment by lifetyper** [comment]
用32位python
